import Head from "next/head";
import { Inter } from "next/font/google";
import { SkipSSR } from "@/SkipSSR";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const App = dynamic(() => import("@/App").then((m) => m.App), { ssr: false });

export default function Home() {
  const [state, setState] = useState(false);

  useEffect(() => {
    setState(true);
  }, []);

  if (!state) return null;

  return (
    <>
      <Head>
        <title>Ngomong</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SkipSSR>
        <App />
      </SkipSSR>
    </>
  );
}
